### ISSUE TITLE
SetUpBundle

### ISSUE THREAD

**Issue by nicolas-bastien** [prestaconcept/PrestaImageBundle#1]
Initialize bundle installation

- [x] composer
- [x] readme, contributing
- [x] travis
- [x] scrutinizer

....

**Comment by nicolas-bastien** [comment]
@J-Ben87 

- https://travis-ci.org/prestaconcept/PrestaImageBundle

I need other files to be initialized to continue

**Comment by J-Ben87** [comment]
Setup complete in master

**Comment by nicolas-bastien** [comment]
https://packagist.org/packages/presta/image-bundle

https://scrutinizer-ci.com/g/prestaconcept/PrestaImageBundle/

Now you can add badges

+ travis is not ok (no need to test on 2.7 if it's not in your composer requires -> so remove 2.7)
+ you can add symfony3 test on travis

**Comment by nicolas-bastien** [comment]
@J-Ben87 + add default bundle class

**Comment by nicolas-bastien** [comment]
@J-Ben87 scrutnizer says code rating is not enabled
https://scrutinizer-ci.com/docs/code_rating_system
