### ISSUE TITLE
Allow user to upload image without manipulation

### ISSUE THREAD

**Issue by nicolas-bastien** [prestaconcept/PrestaImageBundle#16]
This bundle is helpful when we want to resize the image.

But when we an already well formatted image, this bundle low the quality down and this is not really good.

I think the best is to add an another input where the user can upload a file without cropper.

Add an help on it : "Direct upload"

Still render the preview when it's saved.

**Comment by nicolas-bastien** [comment]
@J-Ben87 what do you think of this ?

**Comment by J-Ben87** [comment]
This shouldn't reduce the image quality. We should investigate why it's happening and try to fix it.
However that option might be useful and could be implemented anyway.
