### ISSUE TITLE
How to configure correctly this bundle?

### ISSUE THREAD

**Issue by amadohin** [prestaconcept/PrestaImageBundle#17]
Hi, I have readed the instructions for use this bundle but I can't get it works.

I have installed the bundle with composer
I have registered the bundle in the app.kernel 
In this step I get error because the bundle has a incomplete namespace in the instructions says, write these in app.kernel

       new Vich\UploaderBundle\VichUploaderBundle(),
       new Presta\ImageBundle\ImageBundle(),

But the last bundle should be of this way:

       `new Presta\ImageBundle\PrestaImageBundle(),`

I have configured the twig 
I have configured the route

And finally I have created a form with vichuploader with the ImageFile type like in the documentation say.

But in my twig template nothing show.

* I have imported the theme form from the PrestaImageBundle but nothing happens.

What I'm doing wrong?

Thank's

**Comment by J-Ben87** [comment]
Hi,

Did you [install and load the assets](https://github.com/prestaconcept/PrestaImageBundle#user-content-install-assets)?

**Comment by amadohin** [comment]
Yes, I have installed and load the assets.

I can see, when the form is rendered is not loading the 

image_widget.html.twig

**Comment by J-Ben87** [comment]
Can you show me your form type please?

**Comment by amadohin** [comment]
Yes of course,

I'm not working with form type, I'm creating with Builder

Here my Controller

```
          $media = new OgaMedia();
          $form2 = $this->createFormBuilder($media)
                              ->add('imageFile', FileType::class)
                              ->add('save', SubmitType::class)
                              ->getForm();
```

And my twig template 

```
                    {% form_theme form2 'PrestaImageBundle:form:image_widget.html.twig' %}
                    {{ form_start(form2) }}
                      {{ form_widget(form2.imageFile) }}
                    {{ form_end(form2) }}
```

**Comment by J-Ben87** [comment]
Can you try to use the `Presta\ImageBundle\Form\Type\ImageType` instead of the Symfony `FileType` please?

I realize that it's not documented in the readme that you should use it. If you confirm this is working, I will add it to the doc.

**Comment by amadohin** [comment]
Thank's now it's working.

I had to import the **ImageType** instead **FileType** and set in my FormBuilder **ImageType** instead **FileType** in my input type field.

In addition, I think it's necessary  to document too, than the assets included with the bundle need to be installed and included in twig view with the cropper js and css.

It's a very cool Bundle.

Thank's for help!!

**Comment by amadohin** [comment]
Hi other question, 

How can I set a default size in the cropper?

**Comment by J-Ben87** [comment]
If you have a look in the `Presta\ImageBundle\Form\Type\ImageType`, you will see different options are available.

In your case, you might be interested in the `max_width` and `max_height` options that can be set that way:

```php
// ...
    ->add('image', ImageType::class, [
        'max_width' => 320,
        'max_height' => 180,
    ])
// ...
```

Glad you like the bundle :)

**Comment by amadohin** [comment]
Thank's for all.
