### ISSUE TITLE
Result imagesize is based on preview size

### ISSUE THREAD

**Issue by derpue** [prestaconcept/PrestaImageBundle#24]
Unless i did configure something wrong the resulting image size is the size of the preview (defined by max_width and max_height for which the documentation states that sizes are used for the image preview).

It seems that at the end of the cropper.js in `Cropper.prototype.crop = function()` file the preview canvas is used to generate the imagedata for the upload input field and not the original cropped canvas.

Maybe also the documentation is wrong, and the max_width and max_height are indeed for the size of the uploaded image.

**Comment by J-Ben87** [comment]
You are right: `max_width` and `max_height` are used to define the max width and height of the image preview, which is used to generate the final image.

What is the issue here? Could you be more specific?

**Comment by derpue** [comment]
Thanks for your reply and sorry for not being more specific.

Let's take an example:
* set max_height, max_width to 150px, to get a nice small preview in the form in that size
* take an image, for example a 600x600px one.
* regardless of cropping it to maybe 300x300 or just let it as is
* preview(-canvas) gets filled with an 150x150px (scaled) image
* the hidden input with the base64-imagedata for form-upload gets also wrongly filled with that 150x150px imagedata, but it should be original (cropped) size, not the preview scaled down size
* when examining the uploaded file, it is indeed only 150x150px

it seems to me that `Resources/public/js/cropper.js` Line 193 should be more something like `this.$input.val(this.$container.$preview.children('img').cropper('getCroppedCanvas').toDataURL());` since the image in the `canvas` Variable is already the resized one (from Lines 184-187)

**Comment by J-Ben87** [comment]
Could you please submit a PR with your solution? If it seems to make sense I'll merge it ;)

**Comment by J-Ben87** [comment]
Merged and published on packagist
