### ISSUE TITLE
Remote Loading of images always assumes PNG

### ISSUE THREAD

**Issue by derpue** [prestaconcept/PrestaImageBundle#25]
The action `PrestaImageBundle:Default:urlToBase64` always returnes the fetched remote file as image/png, regardless of the real type.

**Comment by J-Ben87** [comment]
Is that a problem for you? The new image is generated so it doesn't have to depend on the original type.

Feel free to open a PR if you have another implementation ;)

**Comment by derpue** [comment]
No isn't a problem from the practical side. 

_Theoretically_ i could break someday if the browsers decide to correctly honor the declared mimetype in the DataURI but _practically_ they ignore that declared mimetype and "guess" it from the images data.

**Comment by J-Ben87** [comment]
You're right, I'll leave it opened and see if I can spend some time on it soon
