### ISSUE TITLE
Not able to get the translation to work

### ISSUE THREAD

**Issue by shairyar** [prestaconcept/PrestaImageBundle#26]
I have translation enabled in `config.yml`, I even have the messages.en.yml file in which I added `"btn_import_image_local": Import Local` but still i am seeing `btn_import_image_local` as a button text. 

What am i missing here?

**Comment by yann-eugone** [comment]
Translation catalog this bundle uses is `PrestaImageBundle`.

You could either choose to add your translations in this catalog, or change the `translation_domain` option when adding your form field to your form.

**Comment by shairyar** [comment]
Thanks
