### ISSUE TITLE
How to use cropBoxResizable option

### ISSUE THREAD

**Issue by shairyar** [prestaconcept/PrestaImageBundle#27]
I am trying to stop the users from resizing the image beyond minimum height and width and looking at the documentation [this](https://github.com/fengyuanchen/cropper#cropboxresizable) option is what i need. But how do i implement that using the bundle?

I have tried the following but it has no effect.

 ```
       (function(w, $) {
            'use strict';
            $(function() {
                $('.cropper').each(function() {
                    console.log('first ');
                    new Cropper($(this), {
                        cropBoxResizable: false
                    });
                });
            });
        })(window, jQuery);
```

**Comment by J-Ben87** [comment]
Indeed that is not supported yet. Don't ask me why :p

I'll allow passing options during my lunch break and let you know when it's done.

**Comment by shairyar** [comment]
I will really appreciate if this can be added 👍

**Comment by J-Ben87** [comment]
Done, you can now use the `cropper_options` option in your form type to use any cropper options you like.

**Comment by shairyar** [comment]
Thanks alot, how do I pull the latest changes? just do `composer update`?

**Comment by J-Ben87** [comment]
Yes, at least `composer update presta/image-bundle` if you don't want to update all your dependencies

**Comment by shairyar** [comment]
Thanks, this is how I am passing the `cropper_options`
```

            ->add('profileImage', ImageType::class, array(
                'data_class' => null,
	            'cropper_options' => ['cropBoxResizable' => 0]
            ))
```

But it seems to have no effect, I can still resize the crop box

**Comment by shairyar** [comment]
Ah, my bad, I just noticed `data-cropper-options="{{ form.vars.cropper_options }}"` I was using my own view so adding this made it work.

Thank you so much :1st_place_medal:

**Comment by J-Ben87** [comment]
You shouldn't need to. Are you sure your assets are up to date? I mean did you regenerate it (if using a build system like Webpack or the `hard-copy` option with assetic) or clear your browser cache?

**Comment by shairyar** [comment]
Thanks for the tip, yes I am gulp to manage assets, building the assets again made it work.

Thank you so much 👍

**Comment by shairyar** [comment]
I am trying to get a square crop box as i want the images to be 200 by 200

```
            ->add('profileImage', ImageType::class, array(
                'data_class' => null,
	            'cropper_options' => ['cropBoxResizable' => false, 'minCropBoxHeight' => 200, 'minContainerHeight' => 200, 'minCanvasHeight' => 200 ]
            ))
```

But i keep getting a rectangular crop box as you can see in the following screenshot.

![2017-07-04_11-18-13](https://user-images.githubusercontent.com/5089055/27817452-9216a766-60aa-11e7-8bff-03792c01b0f1.jpg)

How to make the crop box square. I am not allowing the users to resize and i just want the cropbox to be square.

**Comment by J-Ben87** [comment]
You should use the `aspect_ratio` option. Have a look at the [ImageType](https://github.com/prestaconcept/PrestaImageBundle/blob/master/Form/Type/ImageType.php) line 89.
