### ISSUE TITLE
How to use setData?

### ISSUE THREAD

**Issue by mkh01** [prestaconcept/PrestaImageBundle#47]
The Bundle is working very well, what i just need is two inputs to define exactly the height and width and then just move the cropped box where i want.

Is it possible without adding extra js or do i have to override the image_widget.html.twig file?

**Comment by J-Ben87** [comment]
Hi,

The only way to do this right now is by adding extra JS.
You'll have to read the value of your 2 inputs and update the data-attributes `data-max-width` and `data-max-height` from the `div.cropper` root element with these values.
