### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by grimmlink** [prestaconcept/PrestaImageBundle#49]
Hi,

I've been trying to use this plugin for a while, and i'm stuck with this:
![image](https://user-images.githubusercontent.com/3241292/46316551-c98b0200-c5d0-11e8-8887-88b3324ae201.png)

I'm using webpack so i added the 2 js files as required:
```
'cropperjs/dist/cropper',
'./vendor/presta/image-bundle/Resources/public/js/cropper.js',
```

and the 2 css files are in my scss as well
```
@import '~cropperjs/dist/cropper.min.css';
@import '../../vendor/presta/image-bundle/Resources/public/css/cropper.css';
```

in my JS script i do
```
    import Cropper from 'cropperjs/dist/cropper';
    ...
    $('.cropper').each(function() {
        new Cropper($(this));
    });
```

and i get this error
> cropper.js:3314 Uncaught Error: The first argument is required and must be an <img> or <canvas> element.
    at new Cropper (cropper.js:3314)
    at HTMLDivElement.<anonymous> (main.js:171)
    at Function.each (jquery.js:354)
    at jQuery.fn.init.each (jquery.js:189)
    at HTMLDocument.<anonymous> (main.js:170)
    at mightThrow (jquery.js:3534)
    at process (jquery.js:3602)

my form type is:
```
$builder
            ->add('picture_file', ImageType::class, [
                'label' => 'user.picture',
                'error_bubbling' => true,
                'translation_domain' => 'messages',
                'required' => false,

                'aspect_ratios' => [
                    [
                        'label' => '1:1',
                        'checked' => 'true',
                        'value' => 1/1,
                    ]
                ],
                'max_width' => 400,
                'max_height' => 400,
                'preview_width' => 512,
                'preview_height' => 512,
            ])
```

**Comment by J-Ben87** [comment]
Hi,

Did you import bootstrap css and js files?
Also I see you are importing `Cropper` from `cropperjs/dist/cropper` when it should be from `bundles/prestaimage/js/cropper`.

My configuration is:

```
# webpack.config.js
const Encore = require('@symfony/webpack-encore');
const path = require('path');

Encore
    // ...
    .addAliases({
        bundles: path.resolve(__dirname, 'public/bundles')
    })
    // ...
;

module.exports = Encore.getWebpackConfig();
```

```
# app.js
import 'bootstrap'
import 'cropper/dist/cropper.min';
import * as Cropper from 'bundles/prestaimage/js/cropper';

$(function() {
    $('.cropper').each(function() {
        new Cropper($(this));
    });
});
```

```
# app.scss
@import "~bootstrap/dist/css/bootstrap.min.css";
@import "~cropper/dist/cropper.min.css";
@import "../../public/bundles/prestaimage/css/cropper.css";
```

```
# config/packages/twig.yaml
twig:
    # ...
    form_themes:
        - "@PrestaImage/form/image_widget.html.twig"
```

```
<?php

namespace App\Form\Type;

use Presta\ImageBundle\Form\Type\ImageType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class FooType extends AbstractType
{
    /**
     * @inheritdoc
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('image', ImageType::class)
        ;
    }
}
```

```
# templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        {# ... #}
        {% block stylesheets %}
            <link rel="stylesheet" href="{{ asset('build/css/app.css') }}">
        {% endblock %}
    </head>
    <body>
        {# ... #}
        {% block javascripts %}
            <script src="{{ asset('build/js/app.js') }}"></script>
        {% endblock %}
    </body>
</html>
```

Let me know if you can't have it work :wink:

**Comment by grimmlink** [comment]
Hi,

Thanks for your reply. I made some modifications to match your config, and it works.
I removed cropperJS from yarn and added cropper instead.

For information:

my js:
```
import 'bootstrap';
import 'cropper/dist/cropper.min';
import * as Cropper from '../../vendor/presta/image-bundle/Resources/public/js/cropper';
```

my scss:
```
@import "~bootstrap/scss/bootstrap";
@import "~cropper/dist/cropper.min.css";
@import '../../vendor/presta/image-bundle/Resources/public/css/cropper.css';
```

config.yml: (symfony 3.4!)
```
twig:
    form_themes:
        - 'form/bootstrap_4_layout.html.twig'
        - 'PrestaImageBundle:form:image_widget.html.twig'
```

formtype:
```
$builder
            ->add('picture_file', ImageType::class);
```

Still have a templating problem though :'(

![image](https://user-images.githubusercontent.com/3241292/46435668-2dd7ce00-c757-11e8-9c9d-36430f0cbc3f.png)

**Comment by J-Ben87** [comment]
Hmm this bundle was developed with bootstrap@3 and unfortunately I didn't have time to upgrade it since bootstrap@4 was released :disappointed: 

If you can't downgrade from bootstrap@4 to bootstrap@3, you might want to open a pull request with the appropriate changes to make the bundle compatible with bootstrap@4

**Comment by grimmlink** [comment]
You could offer 2 different templates and JS, for BS4 and BS3 so people could just choose the ones they need, it will require some JS modification on the "hidden" class which does not exist anymore in BS4 (d-none/d-block for BS4)

I will try to make PR this weekend.

This is what i did:
![image](https://user-images.githubusercontent.com/3241292/46461199-6232a500-c7be-11e8-9230-cb90ed748c8e.png)

**Comment by J-Ben87** [comment]
Thanks!

**Comment by grimmlink** [comment]
Alright, PR is here #51 
Ill close here, thanks for support!
