### ISSUE TITLE
Use newer cropperjs

### ISSUE THREAD

**Issue by Huluti** [prestaconcept/PrestaImageBundle#60]
It seems that https://fengyuanchen.github.io/cropper/ is not maintained any more and has been replaced by https://github.com/fengyuanchen/jquery-cropper by the same developer.

**Comment by J-Ben87** [comment]
Hi, I'll handle this as soon as possible :slightly_smiling_face:

**Comment by Huluti** [comment]
Without jQuery, you can even use : https://github.com/fengyuanchen/cropperjs

**Comment by J-Ben87** [comment]
The documentation is updated, this should work with new cropperjs

**Comment by Huluti** [comment]
@J-Ben87 thank you very much! very appreciated!
