### ISSUE TITLE
URI "/url_to_base64" is not callable.

### ISSUE THREAD

**Issue by treeindark** [prestaconcept/PrestaImageBundle#64]
ERROR : 
`The controller for URI "/url_to_base64" is not callable. Controller "PrestaImageBundle:Default:urlToBase64" does neither exist as service nor as class..`

on SF5

**Comment by treeindark** [comment]
It work but need some change

add in services.yaml 

    ```
Presta\ImageBundle\Controller\DefaultController:
        calls:
            - [setContainer, ['@service_container']]
```

replace Controller by AbstractController in DefaultController

change route 
`_controller: Presta\ImageBundle\Controller\DefaultController:urlToBase64Action`

**Comment by J-Ben87** [comment]
See https://github.com/prestaconcept/PrestaImageBundle/pull/66 which solves all compatibility issues

**Comment by J-Ben87** [comment]
https://github.com/prestaconcept/PrestaImageBundle/pull/66
