### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by treeindark** [prestaconcept/PrestaImageBundle#67]
Cool upgrade SF5 !

but it does not record anymore (all ok , no error) how to find whats' wrong ?

After Trace, 

ligne 25 Base64ToImageTransformer 
if ( !$value['base64']) {
            return null;
        }

And it's good

**Comment by J-Ben87** [comment]
Oops, that was due to an inverted condition...

Solved by https://github.com/prestaconcept/PrestaImageBundle/pull/68
