### ISSUE TITLE
Just resize and upload the image

### ISSUE THREAD

**Issue by macaso** [prestaconcept/PrestaImageBundle#70]
Hello,

Is it possible to use this bundle to just resize and upload the image? I mean: I don't want the Cropper popup (Crop Image) to open after selecting the image. Is this possible?

And another question: if I open a form with an ImageType field in it from a smartphone, will I be able to take a photography with the camera, instead of select a file?

Thank you!

**Comment by J-Ben87** [comment]
Hello,

If you don't need the cropping functionality, I don't think you need this bundle at all. You should probably resize the image server side in PHP directly.
Also I'm not sure if it will start the camera when triggering an image field on a mobile. If this is a native behavior I might, anyway I didn't implement any custom solution in that purpose.

I hope you manage to find what you need.
Cheers
