### ISSUE TITLE
PHP 8 Compatibility

### ISSUE THREAD

**Issue by praswicaksono** [prestaconcept/PrestaImageBundle#74]
Is there any plan to support PHP 8 in near future?

**Comment by yann-eugone** [comment]
Hey @praswicaksono :)

To be honest, I think we just forget to do it.

I think that there is not a lot of work to support it : 
- allowing it in composer.json
- updating .travis.yml testing matrix to run test on it

Do you wish to open a PR for this ?

**Comment by praswicaksono** [comment]
Hi @yann-eugone 

I just created PR for that please kindly to review

**Comment by yann-eugone** [comment]
Just saw it @praswicaksono

Thank you very much for your contribution :)

**Comment by J-Ben87** [comment]
Solved by https://github.com/prestaconcept/PrestaImageBundle/pull/75
