### ISSUE TITLE
Base64ToImageTransformer do not save

### ISSUE THREAD

**Issue by treeindark** [prestaconcept/PrestaImageBundle#83]
I use this bundle since 2years ?(je crois) I make update on my app, there a lots of updates, but after update an error still exist ????

"vendor/presta/image-bundle/Form/DataTransformer/Base64ToImageTransformer.php" 45 lines

reverseTransform don't save !
i make: 

```diff
    public function reverseTransform($value): ?UploadedFile
    {
-        if (!isset($value['base64']) || !$value['base64']) {
+        if (!$value['base64']) {
            return null;
    }
```

Why ???

**Comment by yann-eugone** [comment]
So you issue is that the code enters the early return of the `Base64ToImageTransformer::reverseTransform`.
You updated the code, and removed the `!isset` condition in that if to make it work ?
It seems very weird, did you had the chance to see what's in `$value` at this moment ?
