### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by treeindark** [prestaconcept/PrestaImageBundle#84]
Hello!
Do you plan to upgrade symfony/form to 6.0 ?

**Comment by yann-eugone** [comment]
Hello
I think we just forget it.

I'm pretty confident the bundle is compatible with the `6.x` version : 
- allowing the version in `composer.json`
- adding the version to the testing matrix

Do you want to make a contribution?

**Comment by yann-eugone** [comment]
Released in https://github.com/prestaconcept/PrestaImageBundle/releases/tag/v2.4.0
