### ISSUE TITLE
Problem after updating from 2.4.0 to 2.5.1

### ISSUE THREAD

**Issue by corriol** [prestaconcept/PrestaImageBundle#94]
Hello, 
After upgrading from 2.4.0 to 2.5.1 I've experienced the following error:

Unable to find file "@PrestaImageBundle/Resources/config/routing.yaml" in @PrestaImageBundle/Resources/config/routing.yaml (which is being imported from "/.../config/routes.yaml"). Make sure the "PrestaImageBundle" bundle is correctly registered and loaded in the application kernel class. If the bundle is registered, make sure the bundle path "@PrestaImageBundle/Resources/config/routing.yaml" is not empty.

I've reviewed the Readme file and I don't see where can be the problem.  It seems the bundle doesn't load properly.

I'm using Symfony 5.4 with PHP 8.1 and VichUploader 2.0.1

**Comment by corriol** [comment]
Sorry, I found out the solution. The correct path is "@PrestaImageBundle/config/routing.yaml"

**Comment by corriol** [comment]
Please, update the docs.

**Comment by J-Ben87** [comment]
Done, thanks for the feedback :slightly_smiling_face:
